version: "3.8"

services:
  pgdb:
      container_name: libre_database
      image: postgres:12-alpine
      restart: always
      environment:
        - POSTGRES_HOST=0.0.0.0
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=password
        - POSTGRES_DB=libre
      ports:
        - "9000:5432"  # Forward container port 5432 to localhost port 9000
      volumes: 
        - ./pkg/database/init.sql:/docker-entrypoint-initdb.d/init.sql
        - pgdata:/var/lib/postgresql/data
      networks:
        - web_api
    # extra_hosts:
    #   - "host.docker.internal:host-gateway" # use for mac docker.for.mac.host.internal
  # rest-api:
  #    container_name: libre_rest_api
  #    image: ajalanbrown/libre-api:latest
  #    restart: always
  #    # build the Dockerfile, alternatively use an image.
  #    depends_on:
  #      - "pgdb"
  #    ports:
  #      - "8181:8181"
  #    networks:
  #      - web_api
networks:
  web_api:
    driver: bridge
volumes:
  pgdata: