# POST http://localhost/user/create 
#  Content-Type: application/json

#  {
#      "username": "JohnDoe123",
#      "email": "johndoe@example.com",
#      "password": "mypassword123",
#      "birthday": "1996-03-05T00:00:00Z"
#  }

//GET http://localhost/api/ HTTP/1.1

POST http://localhost/api/user/login 
  Content-Type: application/json

{
      "email": "johndoe@example.com",
      "password": "mypassword123"
     
}