# development enviroment
ENVIROMENT: 
  env: development
SERVER:
  port: 8080
DATABASE:
  host:  localhost #127.0. 0.1 #example.host.db
  port: 9000
  username: postgres
  password: password
  dbname : libre
  max_connections: 100
VERSION:
  release: 0.0.1