# development enviroment
ENVIROMENT: 
  env: development
SERVER:
  port: 8080
DATABASE:
  host:  0.0.0.0 #127.0. 0.1 #example.host.db
  port: 5342
  username: user
  password: password
  dbname : database
  max_connections: 10
VERSION:
  release: 0.0.1